# Generated by Django 2.1.7 on 2019-09-07 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20190822_1126'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpertAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField()),
            ],
        ),
    ]
